name: compound_interest_calculator
description: Calculate compound interest with beautiful charts and insights.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.5
  google_mobile_ads: ^5.3.0
  fl_chart: ^0.70.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
