name: water_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  core_ui:
    path: ../../packages/core_ui
  core_logic:
    path: ../../packages/core_logic
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  google_mobile_ads: ^7.0.0
  shared_preferences: ^2.3.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  core_ui:
    path: ../../packages/core_ui
  core_logic:
    path: ../../packages/core_logic
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
