name: pomodoro_timer
description: A professional Pomodoro Timer app with focus sessions, breaks, and productivity tracking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  core_logic:
    path: ../../packages/core_logic
  core_ui:
    path: ../../packages/core_ui
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^3.2.1
  shared_preferences: ^2.3.5
  google_mobile_ads: ^7.0.0
  audioplayers: ^6.1.0
  fl_chart: ^1.1.1
  dynamic_color: ^1.8.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
