name: feature_fasting
description: "Feature module for Fasting Tracker"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core_logic:
    path: ../../core_logic
  core_ui:
    path: ../../core_ui
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
