name: feature_bmi
description: "Feature module for BMI Calculator"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core_logic:
    path: ../../core_logic
  core_ui:
    path: ../../core_ui
  flutter_riverpod: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
